//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebIDEIBiblio.WSLogisticaSA {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://dei.isep.ipp.pt/", ConfigurationName="WSLogisticaSA.LogisticaSASoap")]
    public interface LogisticaSASoap {
        
        // CODEGEN: Generating message contract since element name devolverNomeEmpresaResult from namespace http://dei.isep.ipp.pt/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://dei.isep.ipp.pt/devolverNomeEmpresa", ReplyAction="*")]
        WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaResponse devolverNomeEmpresa(WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://dei.isep.ipp.pt/calcularDespesasEnvio", ReplyAction="*")]
        double calcularDespesasEnvio(int numeroItens);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverNomeEmpresaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverNomeEmpresa", Namespace="http://dei.isep.ipp.pt/", Order=0)]
        public WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequestBody Body;
        
        public devolverNomeEmpresaRequest() {
        }
        
        public devolverNomeEmpresaRequest(WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class devolverNomeEmpresaRequestBody {
        
        public devolverNomeEmpresaRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class devolverNomeEmpresaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="devolverNomeEmpresaResponse", Namespace="http://dei.isep.ipp.pt/", Order=0)]
        public WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaResponseBody Body;
        
        public devolverNomeEmpresaResponse() {
        }
        
        public devolverNomeEmpresaResponse(WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://dei.isep.ipp.pt/")]
    public partial class devolverNomeEmpresaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string devolverNomeEmpresaResult;
        
        public devolverNomeEmpresaResponseBody() {
        }
        
        public devolverNomeEmpresaResponseBody(string devolverNomeEmpresaResult) {
            this.devolverNomeEmpresaResult = devolverNomeEmpresaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LogisticaSASoapChannel : WebIDEIBiblio.WSLogisticaSA.LogisticaSASoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LogisticaSASoapClient : System.ServiceModel.ClientBase<WebIDEIBiblio.WSLogisticaSA.LogisticaSASoap>, WebIDEIBiblio.WSLogisticaSA.LogisticaSASoap {
        
        public LogisticaSASoapClient() {
        }
        
        public LogisticaSASoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LogisticaSASoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticaSASoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LogisticaSASoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaResponse WebIDEIBiblio.WSLogisticaSA.LogisticaSASoap.devolverNomeEmpresa(WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequest request) {
            return base.Channel.devolverNomeEmpresa(request);
        }
        
        public string devolverNomeEmpresa() {
            WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequest inValue = new WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequest();
            inValue.Body = new WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaRequestBody();
            WebIDEIBiblio.WSLogisticaSA.devolverNomeEmpresaResponse retVal = ((WebIDEIBiblio.WSLogisticaSA.LogisticaSASoap)(this)).devolverNomeEmpresa(inValue);
            return retVal.Body.devolverNomeEmpresaResult;
        }
        
        public double calcularDespesasEnvio(int numeroItens) {
            return base.Channel.calcularDespesasEnvio(numeroItens);
        }
    }
}
